name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t linafarchado/mlopstp:latest .
        
      - name: Push Docker image
        run: |
          docker push linafarchado/mlopstp:latest

      - name: SSH and Deploy on Remote Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 20.86.55.5
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull linafarchado/mlopstp:latest
            docker-compose down
            docker-compose up -d

            sshpass -p "${{ secrets.SSH_PRIVATE_KEY }}" ssh ubuntu@20.86.55.5 -o StrictHostKeyChecking=no << 'EOF'
            EOF